Ficheros iniciales del repositorio [IV-24-25]
wickeet/Tripoli pull request #1
Opened 2024-09-20 10:56 UTC by wickeet

* [ ] ¿Se trata de un problema real del que se tenga conocimiento personal?
Si, un familiar cercano es enfermero y me puede proporcionar información acerca de este problema.
* [ ] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
Para poder acceder a los horarios desde cualquier parte hace falta que la aplicación esté desplegada en la nube
* [ ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
Para poder calcular los horarios hace falta realizar un computo siguiendo las reglas ya especificadas.
* [ ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
Se ha enlazado el acceso al gitignore y a la licencia de uso.
* [ ] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
Con saber el número de usuarios del sistema es suficiente, no es necesario ninguna información extra.
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2024-09-20 11:53 UTC, JJ requested changes
Adicionalmente, no es muy seguro que tengas un .gitignore vacío.

2024-09-20 11:53 UTC, JJ commented on README.md
> +Se pretende crear una aplicación que permita generar horarios de trabajo para enfermeros en un hospital, asegurando el cumplimiento de una serie de restricciones laborales, ya sean el número de horas
Tienes que describir un problema, no una aplicación.

2024-09-22 10:38 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Si, un familiar cercano es enfermero y me puede proporcionar información acerca de este problema.
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
>       Para poder acceder a los horarios desde cualquier parte hace falta que la aplicación esté desplegada en la nube
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
>       Para poder calcular los horarios hace falta realizar un computo siguiendo las reglas ya especificadas.
> 
>     * [x]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
>       `README`?
>       Se ha enlazado el acceso al gitignore y a la licencia de uso.
> 
>     * [x]  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
>       a requerir que el usuario los introduzca?
>       Con saber el número de usuarios del sistema es suficiente, no es necesario ninguna información extra.
> 
>     * [x]  ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
>       todo?

¿Te has dado cuenta de lo que has marcado?

2024-09-22 10:40 UTC, JJ requested changes
Si esto fue lo que se validó en el juego de rol, me temo que no se hizo bien la validación. Si no lo fue, trata de incluir lo que se hizo ahí. En todo caso si no se trata de un problema o idea válido, podrías repetir el juego de rol por tu cuenta o en la próxima clase.
Recuerda que en ingeniería sólo se pueden resolver problemas. Si no existe un problema, o no está bien definido, es imposible que se use ninguna metodología que garantice, de la forma más autónoma posible, que se satisface al cliente y se le entrega un producto de calidad probada.

2024-09-26 07:00 UTC, wickeet commented
@JJ revisión

2024-09-26 07:50 UTC, JJ requested changes
Sigues sin incluir los ficheros de configuración. Por favor, lee [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) para entender qué es lo que se entiende por ficheros de configuración y por qué hace falta entregarlos aquí.

2024-09-26 08:15 UTC, wickeet commented
@JJ revisión

2024-09-27 10:26 UTC, JJ approved these changes
👍

2024-09-27 10:26 UTC, JJ commented on README.md
> +Aquí se puede acceder al .gitignore [.gitignore](./.gitignore)
Esto *no* es un fichero de configuración.

2024-09-27 10:34 UTC, merged