[IV-24-25] Entrega Objetivo 3
wickeet/Tripoli pull request #15
Opened 2024-11-15 12:57 UTC by wickeet

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2024-11-21 07:28 UTC, wickeet commented
@JJ revision

2024-11-21 08:05 UTC, MarioRgzLpz commented
Se me ha asignado revisar esta PR. En general esta bastante bien aunque te puntualizo algunos fallos mínimos.

2024-11-21 08:06 UTC, MarioRgzLpz commented on README.md
> -
Estos cambios no se deben incluir en esta PR. Te recomiendo realizar los cambios en tu rama main y hacer un rebase.

2024-11-21 08:09 UTC, MarioRgzLpz commented on docs/gestor_tareas.md
Aquí no has dicho los criterios que vas a seguir **antes** de elegir la herramienta. Además también es necesarío que definas otros de los posibles gestores de tareas para Go no solo el que has elegido.

2024-11-21 08:10 UTC, MarioRgzLpz commented on go.mod
> +go 1.23.2
Este cambio tampoco debería estar aquí.

2024-11-26 20:53 UTC, hossam1522 reviewed
Buenas! Se me ha encargado revisar tu issue. Realmente, no tengo nada que añadir a lo dicho por el compañero, así que te animo a corregirlo y volver a pedir revisión. ¡Ánimo!

2024-11-28 08:45 UTC, wickeet commented on docs/gestor_tareas.md
Me queda definir otros posibles gestores pero ya he decidido los criterios que voy a seguir, podrías decirme si los ves adecuados?

2024-11-28 08:46 UTC, wickeet commented on README.md
> -
No se por qué aunque he cambiado la rama main y he hecho el rebase, me sigue indicando la modificación, de hecho lo puedes comprobar viendo mi rama main

2024-11-28 08:51 UTC, wickeet commented
gracias @hossam1522 por esperarte a que otro lo corrigiera pese a que te lo pedí en clase varias veces. Me recuerdas a un señor mayor mirando la obra, la mejor generación :100:

2024-12-03 09:49 UTC, wickeet commented
@MarioRgzLpz @hossam1522 me podeis corregir pls

2024-12-04 10:47 UTC, hossam1522 approved these changes
Por mi parte, considero el objetivo aprobado

2024-12-05 08:04 UTC, MarioRgzLpz approved these changes

2024-12-05 08:16 UTC, JJ requested changes
Considera también alguno más, tanto en el caso de herramientas generales como específicas.

2024-12-05 08:16 UTC, JJ commented on Taskfile.yml
> +            - go fmt {{.project_dir}}/...
¿Qué hace `go fmt`? ¿Estás seguro que sólo comprueba la sintaxis?

2024-12-05 08:16 UTC, JJ commented on docs/gestor_tareas.md
> +El lenguaje o formato del archivo de configuración tiene que ser legible y fácil de mantener. Gestores con lenguajes muy complejos o que sean tediosos
¿Como mides la complejidad del lenguaje del gestor?

2024-12-05 08:16 UTC, JJ commented on docs/gestor_tareas.md
> +## 3. Tolerancia a Errores
????

2024-12-05 08:16 UTC, JJ commented on docs/gestor_tareas.md
> +# Goreleaser
Por favor, mirad lo que efectivamente hacen las herramientas. No tenéis más que meteros en la web que habéis enlazado.

2024-12-12 12:23 UTC, wickeet commented
@JJ revision

2024-12-12 13:13 UTC, wickeet commented
@JJ revisión

2024-12-12 13:16 UTC, JJ approved these changes
👍

2024-12-12 13:16 UTC, merged