[IV-24-25] Entrega objetivo 1
wickeet/Tripoli pull request #2
Opened 2024-10-08 08:17 UTC by wickeet

## Sobre los milestones
* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ] ¿El milestone 0 es mínimo *y* viable?
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

## Sobre las historias de usuario
* [ ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2024-10-08 14:16 UTC, juanbarearojo commented
Buenas se me ha asignado revisar tu pr. Te hago un par de puntualizaciones para que puedas mejorarlas.

2024-10-08 14:36 UTC, juanbarearojo commented on docs/milestones.md
> +### [M0] Modelado del problema
Aunque no sea pobre la descripción de este milestone. ¿Has considerado añadir condiciones mas específicas para las condiciones de validación del mismo? Como establece los errores frecuentes del objetivo 1
"Escribir en el primer milestone (milestone 0) "Modelo del problema" no es suficiente. Primero, tiene que describirse qué producto se va a entregar. Segundo, es importante especificar qué se consideraría un modelo válido del problema. Dado que este producto lo va a recibir realmente el estudiante de manos de otro estudiante en el objetivo 2, es esencial que este formule cuidadosamente, para que esa persona lo entienda, qué es lo que espera recibir."

 Piensa que requisitos mínimos tiene que tener le código que te será entregado. Le hará la vida más fácil a tu compañero y a ti mismo en un futuro.
Es fundamental que siempre incluyas criterios, ya sean completamente objetivos o, al menos, que permitan justificar por qué se considera un objetivo alcanzable o no

2024-10-08 14:36 UTC, juanbarearojo commented on docs/milestones.md
> +### [M1] Identificación de Reglas del Convenio
No estoy seguro sobre la existencia de este milestone. Aun siendo algo que tenga totalmente sentido de hacer. Puede que esto tenga que se realizado previo al propio milestone 0. Esto es debido a que antes de plantear una solución o las bases de estas que es el milestone 0 es necesario entender la naturaleza del propio problema. Siendo las restricciones de este mismo parte del entendimiento necesario. No se si el resto de revisores coincidirán con este análisis.

2024-10-08 14:36 UTC, juanbarearojo commented on docs/milestones.md
> +### [M3] Desarrollo de Algoritmo de Asignación de Turnos
Este milestone podemos entender que supone la base de la lógica de negocio. Por ende debería realizarse mucho antes. Cada milestone debemos asegurar que le aporta valor la cliente.

2024-10-08 14:36 UTC, juanbarearojo commented on docs/milestones.md
> +### [M2] Análisis de Disponibilidad del Personal
¿Este milestone que aporta al desarrollo del servicio? Si son necesarias hacer pruebas puede generarse material sintético con un LLM para conseguir este resultado. Bajo este pretexto, este milestone sería algo que haría después de la implementación del servicio. Sería necesario hacer este estudio para cada hospital en el cual se fuera a utilizar.

2024-10-08 14:36 UTC, juanbarearojo commented on docs/milestones.md
> +### [M4] Validación del Algoritmo con Datos Reales
¿Cual es el objetivo de este milestone? Si se ha considerado válido en el anterior milestone cual es le objetivo de realizar este con otro tipo de datos. Si ha cumplido el anterior este también debería cumplirlo. ¿Has considerado la opción de modificar el M3 para que incluya la condiciones de validación de este?

2024-10-08 16:23 UTC, wickeet commented on docs/milestones.md
> +### [M0] Modelado del problema
Es cierto, ahora especificio mejor el dominio del problema

2024-10-08 16:24 UTC, wickeet commented on docs/milestones.md
> +### [M1] Identificación de Reglas del Convenio
Perdona pero no veo que tiene que ver el dominio del problema con las restricciones que va a seguir el algoritmo.

2024-10-08 16:26 UTC, wickeet commented on docs/milestones.md
> +### [M3] Desarrollo de Algoritmo de Asignación de Turnos
A ver si no identifico primero el dominio y las restricciones que va a tener el algoritmo, es un poco inútil adelantar esta parte si luego va a tener que desecharse por no cumplir las normas del convenio

2024-10-08 16:27 UTC, wickeet commented on docs/milestones.md
> +### [M2] Análisis de Disponibilidad del Personal
Es verdad que esto es algo comenté con el profesor en su día con la idea de que los enfermeros pudiesen evitar turnos con según que compañeros, pero para mí también flojea así que seguramente la quite

2024-10-08 16:29 UTC, wickeet commented on docs/milestones.md
> +### [M4] Validación del Algoritmo con Datos Reales
Esta parte la puse en referencia que primero se probaría con datos inventados en el anterior milestone y tras esto, ya sería probarlo con datos reales del hospital donde vaya a ser implementado para ver que funciona correctamente y satisfacía a todos los actores. Igualmente gracias por todos tus comentarios!!

2024-10-08 20:56 UTC, juanbarearojo commented on docs/milestones.md
> +### [M0] Modelado del problema
Lo veo bastante más conciso lo único es esta parte _El código debe incluir ejemplos o pruebas que demuestren cómo las entidades interactúan_. No digo que esté mal pero no sé si es algo que se debería ponerse en la parte de entregable o la de viabilidad

2024-10-08 20:56 UTC, juanbarearojo commented on docs/milestones.md
> +### [M1] Identificación de Reglas del Convenio
Mi punto era que si habías considerado que esté milestone se Incluyera dentro del cero. Vuelvo a lo mismo, veo necesario realizar esta labor pero no se si es una tarea suficientemente separada para que sea su propio milestone. Tampoco he visto ningún milestone asi que no tengo un marco de referencia para poder comparar. Por ende esperaría a ver la opinión del resto de revisores antes de cambiar nada.

2024-10-08 20:59 UTC, juanbarearojo commented on docs/milestones.md
> +### [M2] Análisis de Disponibilidad del Personal
No es una mala funcionalidad la verdad. Pero basado en este nuevo entendimiento adquirido te planteo la posibilidad de reestructurarlo para que quede más claro y luego retrasarlo un par de hitos con perspectiva a futuro.

2024-10-09 08:16 UTC, wickeet commented on docs/milestones.md
> +### [M0] Modelado del problema
@juanbarearojo ya está modificado

2024-10-09 11:39 UTC, Mario25402 commented
Veo un trabajo considerable en este objetivo, por ponerte alguna pequeña pega, creo que el milestone 4 se podria confundir como parte de los criterios de validación del milestone 3 por lo que en mi opinión podría no estar perfectamente, ya que debes tener en cuenta que si vas a aplicar un algoritmo que haga la funcionalidad de la repartición de horas, éste ha de ser eficaz, no valdría un algoritmo que lo haga pero que no cumpla con los requisitos como bien mencionas en la validación del M3.
Si quieres dejar la parte de las estadisticas y la validación de los horarios por parte del personal, puedes enfocar el M4 con esa idea, como funcionalidad extra de la aplicación/proyecto/programa como lo quieras llamar.
Por lo demás muy buen trabajo!!

2024-10-10 06:46 UTC, wickeet commented
@Mario25402 he tenido en cuenta tu recomendación y ya he actualizado el milestone 4

2024-10-10 06:56 UTC, wickeet commented
@JJ revisión

2024-10-10 06:59 UTC, JJ commented
> Veo un trabajo considerable en este objetivo, por ponerte alguna pequeña pega, creo que el milestone 4 se podria confundir como parte de los criterios de validación del milestone 3 por lo que en mi opinión podría no estar perfectamente, ya que debes tener en cuenta que si vas a aplicar un algoritmo que haga la funcionalidad de la repartición de horas, éste ha de ser eficaz, no valdría un algoritmo que lo haga pero que no cumpla con los requisitos como bien mencionas en la validación del M3. Si quieres dejar la parte de las estadisticas y la validación de los horarios por parte del personal, puedes enfocar el M4 con esa idea, como funcionalidad extra de la aplicación/proyecto/programa como lo quieras llamar. Por lo demás muy buen trabajo!!

Por favor, aprobad explícitamente con "approve". Hay un botón para ello en el botón de Review

2024-10-10 07:03 UTC, JJ requested changes
Aparte de lo comentado, lee la introducción [de los errores frecuentes al objetivo 0](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#sobre-el-código-definido)

2024-10-10 07:03 UTC, JJ commented on docs/milestones.md
> +### [M0] Modelado del problema
Si está modificado, resuelve el comentario. Por mi parte, os diría que los milestones no son nunca actividades ("Modelado") sino productos. ¿Crees que podrías mejorar el título de este y los otros milestones en ese sentido?

2024-10-10 07:03 UTC, JJ commented on docs/milestones.md
> ++ **Objetivo**: Realizar un análisis exhaustivo de las Historias de Usuario (HU) para identificar y definir los elementos clave del dominio relacionados con la gestión de turnos de enfermería, establ
¿Hay algún lugar en el guión que os pida los *objetivos*? ¿Qué parte de P, M y V cubren los "objetivos"?

2024-10-10 07:33 UTC, wickeet commented on docs/milestones.md
> ++ **Objetivo**: Realizar un análisis exhaustivo de las Historias de Usuario (HU) para identificar y definir los elementos clave del dominio relacionados con la gestión de turnos de enfermería, establ
@JJ ya he corregido los aspectos mencionados

2024-10-10 07:50 UTC, JJ requested changes
Y vuelve a leer [los errores frecuentes del objetivo 0](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#sobre-el-código-definido). Ya es la cuarta vez que me encuentro lo de las HUs asociadas. Sois libres de emplear vuestro tiempo como queráis, tratando de entender el guión y enviando lo que entendáis para que yo lo corrija (y lo hago con gusto) o mirando lo que ha hecho alguien sin entender lo que ponéis y poniéndolo tal cual para que yo lo corrija también. Pero en este último caso estáis perdiendo el tiempo vosotros, pero también me lo estáis haciendo perder a mi, tiempo que no puedo dedicar a vuestros compañeros. Os agradecería que no lo hiciérais, no ya por vuestro bien ni por el mío, sino simplemente por liberar tiempo del profesor que pueda ayudar a que vuestros compañeros superen los objetivos.

2024-10-10 07:50 UTC, JJ commented on docs/milestones.md
> ++ **Descripción**: Identificar, analizar y documentar todas las normativas aplicables que afectan la gestión de turnos en el hospital, incluyendo aspectos como el número máximo de horas que puede tra
Aquí hablas de las "historias de usuario"

2024-10-10 07:50 UTC, JJ commented on docs/milestones.md
> ++ **HUs asociadas**: [HU001]
Aquí solo hay una "HU asociada". ¿Hay algo en el guión que os pida "Historias asociadas"?

2024-10-10 08:17 UTC, wickeet commented on docs/milestones.md
> ++ **HUs asociadas**: [HU001]
@JJ ya he quitado las historias asociadas, aunque puede reducir la comprensión del por qué se han establecido esos milestones, el M1 carece de sentido sin el pretexto de que ante tantas reglas puede ser tedioso para una persona organizar los turnos. Puede ser que no lo pidiese o que considerase que fuese copia de otro compañero pero lo hice de forma aclarativa para el siguiente objetivo

2024-10-10 09:30 UTC, JJ commented on docs/milestones.md
> ++ **HUs asociadas**: [HU001]
No estoy considerando ni lo uno ni lo otro. Está bien aclarar para el siguiente objetivo, pero hay que hacerlo de forma que realmente aclare, pero sobre todo que siga las prácticas habituales en el área.

2024-10-10 09:32 UTC, JJ requested changes
Por favor, aplica también esto al resto de los milestones, si fuera necesario.

2024-10-10 09:32 UTC, JJ commented on docs/milestones.md
> ++ **Descripción**: Realizar un análisis exhaustivo de las Historias de Usuario (HU) para identificar y definir los elementos clave del dominio relacionados con la gestión de turnos de enfermería, est
¿De cuales historias de usuario?
Por favor, mira los [errores comunes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md):

> Aunque los milestones en principio no tienen por qué tener información sobre las historias de usuario, si hay varias historias de usuario hablar de "modelo del problema" o de "lógica de negocio" no es suficiente, porque las dos historias de usuario (o las 5) pueden tener diferentes aspectos del problema, o incluso ser problemas diferentes

Y antes de que digas que eso eran las "historias asociadas", si lo eran, ¿por qué no las has añadido aquí explícitamente como parte de la definición de cuál es el problema?

2024-10-10 10:03 UTC, wickeet commented on docs/milestones.md
> ++ **Descripción**: Realizar un análisis exhaustivo de las Historias de Usuario (HU) para identificar y definir los elementos clave del dominio relacionados con la gestión de turnos de enfermería, est
@JJ ya se lo he añadido :)

2024-10-10 10:17 UTC, JJ requested changes
Entiendo que estéis un poco hartos. Pero debéis de tratar de entender lo que hacéis y por qué lo hacéis. Intenciones externas a la comprensión del problema y su expresión en lo entregado no llevan casi nunca a un buen fin ni a un escenario win-win para todas las partes involucradas.

2024-10-10 10:17 UTC, JJ commented on docs/milestones.md
> ++ **Descripción**: Realizar un análisis exhaustivo de las Historias de Usuario (de todas) para identificar y definir los elementos clave del dominio relacionados con la gestión de turnos de enfermerí
¿De veras crees que *todas* las historias de usuario se pueden o deben modelizar a la vez? ¿Crees que es una guía adecuada para que una persona empiece a trabajar? 
El trabajo de desarrollo consiste principalmente en dividir el problema para poder abordarlo de forma más sencilla. ¿Crees que poner "de todas" aquí responde más a una intención de "voy a poner lo que sea para pasar al objetivo" o a "voy a hacer fácil a la persona que trabaje en este objetivo 2 su trabajo para que sepa lo que tiene que hacer y si lo que hace está bien"?

2024-10-10 10:41 UTC, wickeet commented on docs/milestones.md
> ++ **Descripción**: Realizar un análisis exhaustivo de las Historias de Usuario (de todas) para identificar y definir los elementos clave del dominio relacionados con la gestión de turnos de enfermerí
@JJ La verdad es que si. Con la HU001 se modeliza tanto los roles de Jefe de Enfermeria como el de Enfermero, además de los elementos clave como son la gestión de turnos o el respeto de la normativa, con la HU002 se modeliza el elemento clave a tener en consecuencia más adelante en el algoritmo de la justicia en la asignación tanto en horas de trabajo como de sueldo y con la HU003 el elemento de que los propios enfermeros puedan modificar turnos cambiando entre sí, que aunque no es algo intrinseco de ningun milestone era una funcionalidad que había tenido en cuenta para el sistema. Puede que la HU003 sea la que más flojea pero considero que todas son importantes para tener una buena comprensión de lo que quiero que sea el proyecto y del resultado final que se espera

2024-10-10 11:25 UTC, wickeet commented on docs/milestones.md
> ++ **Descripción**: Realizar un análisis exhaustivo de las Historias de Usuario (de todas) para identificar y definir los elementos clave del dominio relacionados con la gestión de turnos de enfermerí
@JJ revision

2024-10-10 15:19 UTC, JJ requested changes
Por favor, mira en [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md) qué ocurre cuando sobreespecificas un producto. Básicamente, el producto lo estás haciendo tú:

> Si se dice qué forma debe tener un PMV, ni se deja al desarrollador trabajar sobre el mismo, ni de hecho hace falta que se haga ese trabajo, porque ya se ha hecho. Se debe decir la forma general del producto o qué tiene que hacer el producto para ser válido, no qué contiene, porque para eso es mejor que lo haga directamente quien lo dice.

2024-10-10 15:19 UTC, JJ commented on docs/milestones.md
> ++ **Producto mínimamente viable**: Código que encapsule los elementos fundamentales del dominio, con clases que representen roles como Jefe de Enfermería, Enfermero, y otros elementos esenciales como
Si ya estás diciendo qué clases hay, ¿para qué sirve hacer el modelo? ¿No crees que el modelo deberá desarrollarse para saber lo que hay, que puede que no tenga nada que ver con esto?

2024-10-11 06:38 UTC, wickeet commented on docs/milestones.md
> ++ **Producto mínimamente viable**: Código que encapsule los elementos fundamentales del dominio, con clases que representen roles como Jefe de Enfermería, Enfermero, y otros elementos esenciales como
@JJ revisión

2024-10-11 07:16 UTC, JJ requested changes
La brevedad, sobre todo en los criterios de validación, es una gran virtud. Por favor, si no queréis que os sometan a reglas de validación bizantinas, no me pongáis tampoco a mi a corregirlas.

2024-10-11 07:16 UTC, JJ commented on docs/milestones.md
> +- El diseño debe ser modular y extensible, permitiendo ajustes futuros para incorporar cambios en las normativas o en las reglas de asignación de turnos.
¿Esto te parece algo que pueda comprobar la persona que valide el modelo?

2024-10-11 07:16 UTC, JJ commented on docs/milestones.md
> +- Se considera viable cuando las reglas del convenio, como los límites de horas o los descansos, se puedan integrar con facilidad y puedan ser validadas con pruebas que representen casos reales.
¿Dónde están esas reglas del convenio? Si están en la historia de usuario o user journey, tiene que hacerse como con todo lo demás. Si no están, *no corresponde hacerlo*

2024-10-11 07:53 UTC, wickeet commented on docs/milestones.md
> +- Se considera viable cuando las reglas del convenio, como los límites de horas o los descansos, se puedan integrar con facilidad y puedan ser validadas con pruebas que representen casos reales.
@JJ En el primer user journey:
> Revisión del convenio laboral para verificar los límites de horas, descansos...
No estoy seguro de si se refiere a eso

2024-10-11 08:16 UTC, JJ commented on docs/milestones.md
> +- Se considera viable cuando las reglas del convenio, como los límites de horas o los descansos, se puedan integrar con facilidad y puedan ser validadas con pruebas que representen casos reales.
Y yo no estoy seguro de que entiendas que si está ahí, lo mejor es enlazarlo desde la HU y no ponerlo directamente como criterio de validación, que *no* es el sitio para expresar los deseos de los clientes.

2024-10-11 09:47 UTC, wickeet commented on docs/milestones.md
> +- Se considera viable cuando las reglas del convenio, como los límites de horas o los descansos, se puedan integrar con facilidad y puedan ser validadas con pruebas que representen casos reales.
@JJ ya está corregido

2024-10-11 10:39 UTC, JJ reviewed
Ya te queda poquísimo

2024-10-11 10:39 UTC, JJ commented on docs/milestones.md
>  - La documentación debe incluir una descripción clara de cada entidad y su propósito dentro del dominio.
¿Qué os he dicho de la documentación?

2024-10-11 10:39 UTC, JJ commented on docs/milestones.md
> ++ **Criterio de Validación**: El algoritmo será validado mediante pruebas con conjuntos de datos de prueba, asegurando que el reparto de los turnos es justo. El entregable será considerado viable cua
¿Tú crees realmente que un revisor apruebe los resultados de las pruebas?

2024-10-11 10:48 UTC, wickeet commented on docs/milestones.md
> ++ **Criterio de Validación**: El algoritmo será validado mediante pruebas con conjuntos de datos de prueba, asegurando que el reparto de los turnos es justo. El entregable será considerado viable cua
@JJ ya he tenido en cuenta sus comentarios y lo he corregido

2024-10-11 11:25 UTC, wickeet commented on docs/milestones.md
> +- El diseño debe ser modular y extensible, permitiendo ajustes futuros para incorporar cambios en las normativas o en las reglas de asignación de turnos.
@JJ ya he corregido esto

2024-10-11 11:47 UTC, JJ approved these changes
👍

2024-10-11 11:47 UTC, merged