[IV-24-25] Objetivo 2
wickeet/Tripoli pull request #7
Opened 2024-10-18 11:28 UTC by hossam1522

## Sobre la estructura del repositorio

* [ ] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [ ] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?

## Sobre el planteamiento

* [ ] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [ ] ¿Los issues representan un problema, y no una tarea?

## Sobre el análisis del problema

* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [ ] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

## Sobre el código

* [ ] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [ ] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [ ] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [ ] ¿Todos los issues creados están relacionados con a una HU?
* [ ] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [ ] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [ ] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2024-10-23 11:10 UTC, hossam1522 commented
Listo para revisión @wickeet

2024-10-24 07:11 UTC, hossam1522 commented
Tienes razón, no lo había tenido en cuenta.

2024-10-24 07:52 UTC, wickeet commented
Además, aunque no es erróneo, tal vez sea más adecuado en las normas de convenio en vez de un mínimo de horas de descanso, algo relacionado con el límite de días seguidos que alguien puede trabajar. En un caso real, los enfermeros tienen un límite de un máximo de 7 días seguidos, y si se llega a dar al día siguiente sí o sí tiene que descansar.

2024-10-24 08:09 UTC, wickeet approved these changes
Una vez realizados los cambios mencionados, me parece que el PR es adecuado y lo apruebo :+1:

2024-10-24 08:37 UTC, hossam1522 commented
Listo para revisión @JJ

2024-10-24 10:21 UTC, JJ requested changes
No he hecho una revisión exhaustiva, pero sí tendrías que revisar todo el código (por parte de los dos) para ver realmente si estás modelizando correctamente el dominio del problema,  lo estás haciendo con un modelo mínimo que incluya solamente lo necesario (es decir, especificado en las HUs)

2024-10-24 10:21 UTC, JJ commented on internal/enfermeria.go
> +	Jefe      Enfermero
¿Qué parte de #8 o de #10 dicen que tiene que incluirse explícitamente en la estructura de datos otra estructura que incluya quién es el jefe de enfermería?
¿Hay alguna HU que indique se se va a trabajar con ese atributo?

2024-10-24 10:21 UTC, JJ commented on internal/enfermero.go
> +	HoraInicio time.Time
¿Se puede comenzar a las 13:37? ¿En qué historia de usuario lo dice?

2024-10-24 10:21 UTC, JJ commented on internal/enfermero.go
> +	ID               int
¿Los objetos valor tienen ID?

2024-10-25 11:06 UTC, hossam1522 commented on internal/enfermeria.go
> +	Jefe      Enfermero
Resuelto en https://github.com/wickeet/Tripoli/pull/7/commits/523923e5e334c3334db8a3b07bbb4152479c0739

2024-10-25 11:14 UTC, hossam1522 commented on internal/enfermero.go
> +	ID               int
Resuelto en https://github.com/wickeet/Tripoli/pull/7/commits/0f0d84ac507f090a52d1f92452517b6cba36bd64

2024-10-30 23:01 UTC, hossam1522 commented on internal/enfermero.go
> +	HoraInicio time.Time
Resuelto en https://github.com/wickeet/Tripoli/pull/7/commits/1ef527d6190a02bb52b8fdb6d512f5cb9b8abf77

2024-10-30 23:02 UTC, hossam1522 commented
¿Podrías volverme a revisar el código, @wickeet? He realizado bastantes cambios y me gustaría tener tu aprobación antes de pedírsela al profesor.

2024-10-31 07:44 UTC, wickeet approved these changes
yo veo bien los cambios realizados :+1:

2024-10-31 07:49 UTC, hossam1522 commented
Listo para revisión @JJ

2024-10-31 08:12 UTC, wickeet commented
Lo discutido con el profesor nos ha recomendado lo siguiente:
revisar issue wickeet#8 y wickeet#9,
cambiar la representacion de enfermeria (minimo)

2024-10-31 12:11 UTC, hossam1522 commented
Una pequeña revisión por aquí porfa :stuck_out_tongue: @wickeet

2024-10-31 16:23 UTC, JJ requested changes
Por favor, tratad de no inventar estructuras. Si se pide que apuntéis al issue en el que estáis trabajando es para eso; si se ve que lo que escribís no tiene nada que ver con el issue el código no sería válido.

2024-10-31 16:23 UTC, JJ commented on internal/enfermero.go
> +	apellidos string
¿Hay algo en alguna HU que diga que hay que identificar a un enfermero por nombre *y* apellidos?

2024-10-31 16:23 UTC, JJ commented on internal/enfermero.go
> +	rol       string
¿Qué tiene que ver esto con las "preferencias y disponibilidad de un enfermero"? ¿Y los nombres y apellidos?

2024-11-01 22:17 UTC, hossam1522 commented on internal/enfermero.go
> +	apellidos string
Resuelto en https://github.com/wickeet/Tripoli/pull/7/commits/c78825c787cd18b86e6c9058b604ffe727378c60

2024-11-01 22:17 UTC, hossam1522 commented on internal/enfermero.go
> +	rol       string
Resuelto en https://github.com/wickeet/Tripoli/pull/7/commits/c78825c787cd18b86e6c9058b604ffe727378c60

2024-11-01 22:23 UTC, hossam1522 commented
Listo para revisión @JJ

2024-11-02 07:57 UTC, JJ requested changes
Por otro lado, ¿dónde está el conjunto de turnos que va a hacer una persona? ¿Eso habéis decidido no incluirlo? ¿No forma parte del modelo?

2024-11-02 07:57 UTC, JJ commented on internal/turno.go
> +	inicio    time.Time
¿Un turno puede empezar a las 3:35:22?

2024-11-02 07:57 UTC, JJ commented on internal/turno.go
> +	fin       time.Time
¿Un turno puede terminar a las 3:25:10 después de empezar a la hora de arriba?

2024-11-04 11:50 UTC, hossam1522 commented on internal/turno.go
> +	fin       time.Time
Resuelto en https://github.com/wickeet/Tripoli/pull/7/commits/c8ac4d13b145d3fec24a204acf28480cb7338237

2024-11-04 11:51 UTC, hossam1522 commented on internal/turno.go
> +	inicio    time.Time
Por mi parte, no lo considero un problema ni algo descabellado realmente. ¿Qué opinas, @wickeet?

2024-11-05 08:34 UTC, wickeet commented on internal/turno.go
> +	inicio    time.Time
entiendo que el comentario hace referencia a que inicio debería estar limitado a que sean por ejemplo las 9 de la mañana, pero representar la hora de inicio con time.Time me parece bien. Igual habría que investigar alguna forma de limitarlo

2024-11-05 09:26 UTC, hossam1522 commented
Listo para revisión @JJ

2024-11-05 13:33 UTC, JJ requested changes
Creo que si tratáis de modelar *realmente* las horas de entrada y salida de los turnos en vez de simplemente considerar que es "una hora cualquiera" os acercaréis un poco más a completar el modelo que requiere este milestone. Si es pertinente, abrid otro issue.

2024-11-05 13:33 UTC, JJ commented on internal/normasConvenio.go
> +	fechasFestivas    []time.Time
¿las fechas festivas pueden ser las 3:33:45 del 23 de Noviembre de 2015?

2024-11-05 13:33 UTC, JJ commented on internal/turno.go
> +	inicio    time.Time
@hossam1522 ¿lo has cerrado después de que @wickeet diga "habría que investigar alguna forma de limitarlo"? ¿Qué es lo que dice la HU correspondiente?

2024-11-06 13:32 UTC, hossam1522 commented on internal/turno.go
> +	inicio    time.Time
Resuelto en https://github.com/wickeet/Tripoli/pull/7/commits/4189d54ae5f87c4a3d4b8cb8756bfad094b8dac1 y en https://github.com/wickeet/Tripoli/pull/7/commits/82cc65b5b5c96e97ea9183806b3823d47c16c62d

2024-11-06 13:33 UTC, hossam1522 commented
Listo para revisión @JJ

2024-11-06 17:36 UTC, JJ approved these changes
:+1: Realmente deberías haber considerado usar el sistema de tipos para hacer lo mismo, pero la solución es válida si a @wickeet se lo parece.

2024-11-07 07:56 UTC, merged